Initial commit

diff --git a/s2i/bin/assemble b/s2i/bin/assemble
--- a/s2i/bin/assemble
+++ b/s2i/bin/assemble
@@ -89,34 +89,45 @@ fi
 
 if [ "$NODE_ENV" != "production" ]; then
 
-	echo "---> Building your Node application from source"
-	npm install
+	if [ ! -z "$YARN_ENABLED" ]; then
+		echo "---> Using 'yarn install' with YARN_ARGS"
+		yarn install $YARN_ARGS
+	else 
+		echo "---> Building your Node application from source"
+		npm install
+	fi
 
 else
 
-	echo "---> Installing all dependencies"
-	NODE_ENV=development npm install
+	if [ ! -z "$YARN_ENABLED" ]; then
+		echo "---> Using 'yarn install' with YARN_ARGS"
+		npx yarn install $YARN_ARGS
+		$YARN_BUILD
+	else
+		echo "---> Installing all dependencies"
+		NODE_ENV=development npm install
 
-	#do not fail when there is no build script
-	echo "---> Building in production mode"
-	npm run build --if-present
+		#do not fail when there is no build script
+		echo "---> Building in production mode"
+		npm run build --if-present
 
-	echo "---> Pruning the development dependencies"
-	npm prune
+		echo "---> Pruning the development dependencies"
+		npm prune
 
-	# Clear the npm's cache and tmp directories only if they are not a docker volumes
-	NPM_CACHE=$(npm config get cache)
-	if ! mountpoint $NPM_CACHE; then
-		echo "---> Cleaning the npm cache $NPM_CACHE"
-		#As of npm@5 even the 'npm cache clean --force' does not fully remove the cache directory
-		# instead of $NPM_CACHE* use $NPM_CACHE/*.
-		# We do not want to delete .npmrc file.
-		rm -rf "${NPM_CACHE:?}/"
-	fi
-	NPM_TMP=$(npm config get tmp)
-	if ! mountpoint $NPM_TMP; then
-		echo "---> Cleaning the $NPM_TMP/npm-*"
-		rm -rf $NPM_TMP/npm-*
+		# Clear the npm's cache and tmp directories only if they are not a docker volumes
+		NPM_CACHE=$(npm config get cache)
+		if ! mountpoint $NPM_CACHE; then
+			echo "---> Cleaning the npm cache $NPM_CACHE"
+			#As of npm@5 even the 'npm cache clean --force' does not fully remove the cache directory
+			# instead of $NPM_CACHE* use $NPM_CACHE/*.
+			# We do not want to delete .npmrc file.
+			rm -rf "${NPM_CACHE:?}/"
+		fi
+		NPM_TMP=$(npm config get tmp)
+		if ! mountpoint $NPM_TMP; then
+			echo "---> Cleaning the $NPM_TMP/npm-*"
+			rm -rf $NPM_TMP/npm-*
+		fi
 	fi
 
 fi
